# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">=1.4.0"
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "2.9.11"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
    pihole = {
      source  = "ryanwholey/pihole"
      version = "0.0.12"
    }
  }
}

provider "proxmox" {
  pm_api_url      = "https://192.168.0.100:8006/api2/json"
  pm_tls_insecure = true
}

provider "pihole" {
  url      = "http://pihole.kumpdev.com/"
  password = var.pihole_password
}
